apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eve-tracker
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      backend=gitea.yourdomain.com/CHANGEME/eve-tracking-jobs-backend,
      frontend=gitea.yourdomain.com/CHANGEME/eve-tracking-jobs-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:eve-tracker/gitea-registry
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:eve-tracker/gitea-registry
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/CHANGEME/eve-tracker-k8s.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: eve-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
